version: 2

seeds:
  - name: sales
    description: "Sample sales transaction data"
    columns:
      - name: order_id
        tests:
          - not_null
          - unique

      - name: order_date
        tests:
          - not_null

      - name: customer_id
        tests:
          - not_null

      - name: status_code
        tests:
           - not_null
          
  - name: employees
    columns:
      - name: employee_id
        tests: 
          - not_null
          - unique

  - name: departments
    columns:
      - name: department_id
        tests: 
           - not_null
           - unique